version: '3'

services:

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    tty: true
    networks:
      - desafionode
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node-api
      - MYSQL_ROOT_PASSWORD=root
    
  api:
    image: alexaoliveira/node-api
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node /app/index.js
    build:
      context: ./api
      dockerfile: Dockerfile
    tty: true
    networks:
      - desafionode
    depends_on:
      - db

  proxy:
    image: alexaoliveira/proxy
    container_name: proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:80
    networks:
      - desafionode
    depends_on:
      - api

networks:
  desafionode:
    driver: bridge